[profile.default]
src = "src"               # Where your contract source files live
out = "out"              # Where compiled artifacts (ABI, bytecode) are stored
libs = ["lib"]           # Where dependencies are installed (forge install)
optimizer = true         # Enable Solidity optimizer
optimizer_runs = 30000   # How many times you expect each function to run
via_ir = true           # Use Yul IR pipeline for better optimizations
version = "0.8.30"      # solc version


[profile.intense]
optimizer = true
optimizer_runs = 1000000
via_ir = true
version = "0.8.30"

# forge test --fuzz
[fuzz]
runs = 10000
max_test_rejects = 65536
seed = "0x3e8" # 1000
directoy_weight = 40 # 40% - 40% of the time, the fuzzer will choose to run the test

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
