[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# 1. why?
[profile.intense]
optimizer = true
optimizer_runs = 20000
via_ir = true

# 2. why?
[fuzz]
runs = 10000
max_test_rejects = 65536
seed = "0x3e8"
directoy_weight = 40

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
