[profile.default]
version = "0.8.28"      # solc version
src = "src"               # Where your contract source files live
out = "out"              # Where compiled artifacts (ABI, bytecode) are stored
libs = ["lib"]           # Where dependencies are installed (forge install)
optimizer = true         # Enable Solidity optimizer
optimizer_runs = 30000   # How many times you expect each function to run
via_ir = true           # Use Yul IR pipeline for better optimizations
remappings = [
    "solmate/=lib/solmate/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]


[profile.intense]
version = "0.8.30"
optimizer = true
optimizer_runs = 1000000
via_ir = true
remappings = [
    "solmate/=lib/solmate/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# forge test --fuzz
[fuzz]
version = "0.8.30"
runs = 10000
max_test_rejects = 65536
seed = "0x3e8" # 1000
directoy_weight = 40 # 40% - 40% of the time, the fuzzer will choose to run the test
remappings = [
    "solmate/=lib/solmate/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
