name: Security Analysis

on:
    - push

env:
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14.0

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10.11.0
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Install Slither and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install slither-analyzer
                pip install solc-select
                solc-select install 0.8.28
                solc-select use 0.8.28
                
            - name: Run Slither
              run: pnpm run analysis
